/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-05-24 15:48:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class changePassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel='stylesheet' href='webjars/bootstrap/3.0.0/css/bootstrap.css'>\r\n");
      out.write("<script src=\"resources/js/validator.js\"></script>\r\n");
      out.write("<link rel='stylesheet' href='resources/sweetalert-master/dist/sweetalert.css'>\r\n");
      out.write("<script>\r\n");
      out.write("$(window).load(function()\r\n");
      out.write("{\r\n");
      out.write("  \r\n");
      out.write("   $('.hold-widgets').validator().on('submit', function (e) {\r\n");
      out.write("  if (e.isDefaultPrevented()) {\r\n");
      out.write("    // handle the invalid form...\r\n");
      out.write("     changePassword();\r\n");
      out.write("  } else {\r\n");
      out.write("    // everything looks good!\r\n");
      out.write("    alert(\"look good\");\r\n");
      out.write("  }\r\n");
      out.write("}) \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//call to change password\r\n");
      out.write("var changePassword = function()\r\n");
      out.write("{\r\n");
      out.write("  var http = new XMLHttpRequest();\r\n");
      out.write("  var newPassword = document.getElementById(\"inputPassword\").value;\r\n");
      out.write("  var oldPassword = document.getElementById(\"oldpassword\").value;\r\n");
      out.write("\tvar url = \"http://localhost:8080/AutomaticAccessSystem/submitpassword?oldpass=\"+oldPassword+\"&newpass=\"+newPassword;\r\n");
      out.write("\thttp.open(\"GET\", url, true);\r\n");
      out.write("\t\r\n");
      out.write("\thttp.onreadystatechange = function() {\r\n");
      out.write("\t    var status = http.status;\r\n");
      out.write("\t    if(http.readyState == 4 && http.status == 200) {\r\n");
      out.write("\t       \r\n");
      out.write("\t        var obj = JSON.parse(http.responseText);\r\n");
      out.write("\t        var failedState = 0;  \r\n");
      out.write("\t        if(obj.code == 0)\r\n");
      out.write("\t        {\r\n");
      out.write("\t           swal(\"Oopps\",\" The password does not exist\", \"error\");   \r\n");
      out.write("\t        }\r\n");
      out.write("\t        else\r\n");
      out.write("\t        {\r\n");
      out.write("\t          swal(\"Success\",\" You have successfully changed your password\", \"success\");   \r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t    }\r\n");
      out.write("\t    else\r\n");
      out.write("\t    {\r\n");
      out.write("\t    \tresponse = \"\";\r\n");
      out.write("\t    }\r\n");
      out.write("   }\r\n");
      out.write("   http.send(null);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"change-password-container\">\r\n");
      out.write("<form autocomplete=\"off\" class=\"hold-widgets\" role=\"form\" data-toggle=\"validator\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-widgets\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<input type=\"password\" placeholder=\"Old password\" id=\"oldpassword\" class=\"form-control\" required=\"required\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<input type=\"password\" data-minlength=\"6\" placeholder=\"New password\" class=\"form-control\" id=\"inputPassword\"/>\r\n");
      out.write(" <div class=\"help-block\">Minimum of 6 characters</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<input type=\"password\" placeholder=\"Confirm password\" class=\"form-control\"  id=\"inputPasswordConfirm\" data-match=\"#inputPassword\" data-match-error=\"Whoops, these don't match\" placeholder=\"Confirm\" required>\r\n");
      out.write("<div class=\"help-block with-errors\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div> <button type=\"submit\" class=\"btn btn-primary\">Submit</button></div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
