/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-05-26 09:53:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("window.onload = function ()\r\n");
      out.write("{\r\n");
      out.write("    swal(\"Yap man\", \"gotcha\", \"success\");\r\n");
      out.write("\tvar runAsync = getDetails();\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var getDetails = function()\r\n");
      out.write("{\r\n");
      out.write("  var http = new XMLHttpRequest();\r\n");
      out.write("\tvar url = \"http://localhost:8080/AutomaticAccessSystem/details?studentNumber=858874\";\r\n");
      out.write("\thttp.open(\"GET\", url, true);\r\n");
      out.write("\t\r\n");
      out.write("\thttp.onreadystatechange = function() {\r\n");
      out.write("\t    var status = http.status;\r\n");
      out.write("\t    if(http.readyState == 4 && http.status == 200) {\r\n");
      out.write("\t       \r\n");
      out.write("\t        var obj = JSON.parse(http.responseText);\r\n");
      out.write("\t        document.getElementById(\"student-number\").innerHTML = obj.studentNumber;\r\n");
      out.write("\t        document.getElementById(\"course\").innerHTML = obj.course;\r\n");
      out.write("\t        document.getElementById(\"course-duration\").innerHTML = obj.courseDuration;\r\n");
      out.write("\t        document.getElementById(\"tuition\").innerHTML = obj.tuition;\r\n");
      out.write("\t        toggle_visibility(\"preloader6\");\r\n");
      out.write("\t        \r\n");
      out.write("\t    }\r\n");
      out.write("\t    else\r\n");
      out.write("\t    {\r\n");
      out.write("\t    \tresponse = \"\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   }\r\n");
      out.write("   http.send(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  function toggle_visibility(id) {\r\n");
      out.write("       var e = document.getElementById(id);\r\n");
      out.write("       if(e.style.display == 'block')\r\n");
      out.write("          e.style.display = 'none';\r\n");
      out.write("       else\r\n");
      out.write("          e.style.display = 'block';\r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("  \r\n");
      out.write("    $(document).ready(function()\r\n");
      out.write("    {\r\n");
      out.write(" \t\tvar str=location.href.toLowerCase();\r\n");
      out.write("        $('.navigation li a').each(function()\r\n");
      out.write("         {\r\n");
      out.write("                if (str.indexOf(this.href.toLowerCase()) > -1) \r\n");
      out.write("                {\r\n");
      out.write("\t\t\t\t\t\t$(\"li.highlight\").removeClass(\"highlight\");\r\n");
      out.write("                        $(this).parent().addClass(\"highlight\"); \r\n");
      out.write("                }\r\n");
      out.write("         });\r\n");
      out.write("          \r\n");
      out.write("\t\t$('li.highlight').parents().each(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\tif ($(this).is('li'))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t$(this).addClass(\"highlight\"); \r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t   });  \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"student-name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&nbsp;&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${secondName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("<div id=\"image-container\">\r\n");
      out.write("  <img src=\"resources/images/profile.png\" />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"student-profile-container\">\r\n");
      out.write("<div class=\"student-profile\">\r\n");
      out.write("<div id=\"preloader6\"></div>\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td style=\"padding-right:120px; padding-bottom:20px;\">Student number</td><td id=\"student-number\"></td></tr>\r\n");
      out.write("<tr><td style=\"padding-right:120px; padding-bottom:20px;\">Course</td><td id=\"course\">Computer engineering</td></tr>\r\n");
      out.write("<tr><td style=\"padding-right:120px; padding-bottom:20px;\">Course duration</td><td id=\"course-duration\">4</td></tr>\r\n");
      out.write("<tr><td style=\"padding-right:120px; padding-bottom:20px;\">Tuition</td><td id=\"tuition\">858488</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
